# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$fill\
$python\
$rust\
$docker_context\
$container\
$jobs\
$cmd_duration\
$line_break\
$character
"""

palette = "nord"

[palettes.nord]
dark_blue = '#5E81AC'
blue = ' #81A1C1'
teal = '#88C0D0'
red = '#BF616A'
orange = '#D08770'
green = '#A3BE8C'
yellow = '#EBCB8B'
purple = '#B48EAD'

[fill]
symbol = ' '

[directory]
style = 'bold fg:dark_blue'
format = '[$path ]($style)'
truncation_length = 3
truncation_symbol = '󰇘/'
truncate_to_repo = false
home_symbol = ' '

[directory.substitutions]
'Documents' = '󰈙'
'Downloads' = ''
'Pictures' = ''

[cmd_duration]
min_time = 500
style = 'bold fg:gray'
format = '[$duration]($style)'

[jobs]
symbol = ''
style = 'red'
number_threshold = 1
format = '[$symbol]($style)'

[git_branch]
style = 'fg:green'
symbol = ' '
format = '[on](white) [$symbol$branch ]($style)'

[git_status]
style = 'fg:green'
format = '([$all_status$ahead_behind]($style) )'
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[container]
symbol = ''

[python]
style = 'teal'
symbol = ' '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
# pyenv_version_name = true
# pyenv_prefix = ""

